"""initial schema

Revision ID: d2c48c0bf3f1
Revises: 
Create Date: 2026-04-23 19:10:05.765216
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd2c48c0bf3f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ch_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_number', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ch_snapshots_company_number'), 'ch_snapshots', ['company_number'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_number', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('company_status', sa.String(length=100), nullable=True),
    sa.Column('company_type', sa.String(length=100), nullable=True),
    sa.Column('sic_codes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_company_number'), 'companies', ['company_number'], unique=True)
    op.create_table('pipeline_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('llm_provider', sa.String(length=100), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('inference_prompt_version', sa.String(length=50), nullable=False),
    sa.Column('ranking_prompt_version', sa.String(length=50), nullable=False),
    sa.Column('scoring_weights', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_configs_config_hash'), 'pipeline_configs', ['config_hash'], unique=True)
    op.create_table('lookups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ch_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_config_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verified_domain_id', sa.UUID(), nullable=True),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ch_snapshot_id'], ['ch_snapshots.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['pipeline_config_id'], ['pipeline_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookups_company_id'), 'lookups', ['company_id'], unique=False)
    op.create_index(op.f('ix_lookups_job_id'), 'lookups', ['job_id'], unique=True)
    op.create_table('domain_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lookup_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=500), nullable=False),
    sa.Column('discovered_via_redirect', sa.Boolean(), nullable=False),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('ranking_confidence', sa.Float(), nullable=True),
    sa.Column('ranking_reasoning', sa.Text(), nullable=True),
    sa.Column('is_primary_candidate', sa.Boolean(), nullable=False),
    sa.Column('is_squatted_or_parked', sa.Boolean(), nullable=False),
    sa.Column('dns_data', sa.JSON(), nullable=True),
    sa.Column('https_data', sa.JSON(), nullable=True),
    sa.Column('ssl_data', sa.JSON(), nullable=True),
    sa.Column('whois_data', sa.JSON(), nullable=True),
    sa.Column('content_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lookup_id'], ['lookups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_candidates_domain'), 'domain_candidates', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_candidates_lookup_id'), 'domain_candidates', ['lookup_id'], unique=False)
    op.create_table('inference_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lookup_id', sa.UUID(), nullable=False),
    sa.Column('candidates_raw', sa.JSON(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lookup_id'], ['lookups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lookup_id')
    )
    op.create_table('ranking_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lookup_id', sa.UUID(), nullable=False),
    sa.Column('primary_domain_id', sa.UUID(), nullable=True),
    sa.Column('primary_domain', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lookup_id'], ['lookups.id'], ),
    sa.ForeignKeyConstraint(['primary_domain_id'], ['domain_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lookup_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranking_summaries')
    op.drop_table('inference_results')
    op.drop_index(op.f('ix_domain_candidates_lookup_id'), table_name='domain_candidates')
    op.drop_index(op.f('ix_domain_candidates_domain'), table_name='domain_candidates')
    op.drop_table('domain_candidates')
    op.drop_index(op.f('ix_lookups_job_id'), table_name='lookups')
    op.drop_index(op.f('ix_lookups_company_id'), table_name='lookups')
    op.drop_table('lookups')
    op.drop_index(op.f('ix_pipeline_configs_config_hash'), table_name='pipeline_configs')
    op.drop_table('pipeline_configs')
    op.drop_index(op.f('ix_companies_company_number'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_ch_snapshots_company_number'), table_name='ch_snapshots')
    op.drop_table('ch_snapshots')
    # ### end Alembic commands ###
